-- ================================================
-- HRMS SCHEMA EXPORT (Supabase Compatible)
-- ================================================

-- -----------------------------
-- Table: approval_logs
-- -----------------------------
CREATE TABLE approval_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    module VARCHAR(50) NOT NULL,
    request_id INTEGER NOT NULL,
    workflow_id INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    approver_id INTEGER NOT NULL,
    status VARCHAR(20),
    acted_at TIMESTAMP,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: attendance
-- -----------------------------
CREATE TABLE attendance (
    attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER,
    date DATE NOT NULL,
    check_in TIMESTAMP,
    check_out TIMESTAMP,
    total_hours NUMERIC,
    status VARCHAR(20),
    created_at TIMESTAMP DEFAULT now(),
    late_minutes INTEGER,
    overtime_minutes INTEGER,
    break_minutes INTEGER,
    shift_id INTEGER,
    net_hours NUMERIC,
    is_late BOOLEAN,
    is_early_checkout BOOLEAN,
    early_exit_minutes INTEGER,
    is_overtime BOOLEAN,
    is_weekend BOOLEAN,
    is_holiday BOOLEAN,
    is_night_shift BOOLEAN,
    is_payroll_locked BOOLEAN,
    locked_at TIMESTAMP,
    override_comment TEXT,
    overridden_by INTEGER,
    overridden_at TIMESTAMP,
    early_overtime_minutes INTEGER,
    PRIMARY KEY (attendance_id)
);

-- -----------------------------
-- Table: attendance_events
-- -----------------------------
CREATE TABLE attendance_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER,
    event_type VARCHAR(20) NOT NULL,
    event_time TIMESTAMP NOT NULL,
    source VARCHAR(40),
    meta JSONB,
    created_at TIMESTAMP DEFAULT now(),
    session_id BIGINT,
    PRIMARY KEY (event_id)
);

-- -----------------------------
-- Table: attendance_policies
-- -----------------------------
CREATE TABLE attendance_policies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    late_grace_minutes INTEGER NOT NULL,
    early_exit_grace_minutes INTEGER NOT NULL,
    full_day_fraction DOUBLE PRECISION NOT NULL,
    half_day_fraction DOUBLE PRECISION NOT NULL,
    night_shift_enabled BOOLEAN,
    overtime_enabled BOOLEAN,
    active BOOLEAN,
    created_at TIMESTAMP DEFAULT now(),
    early_checkin_grace_minutes INTEGER,
    early_checkin_action VARCHAR(10),
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: attendance_sessions
-- -----------------------------
CREATE TABLE attendance_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER NOT NULL,
    shift_id INTEGER,
    session_date DATE NOT NULL,
    check_in TIMESTAMP NOT NULL,
    check_out TIMESTAMP,
    total_work_seconds INTEGER,
    total_break_seconds INTEGER,
    is_closed BOOLEAN,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (session_id)
);

-- -----------------------------
-- Table: bank_details
-- -----------------------------
CREATE TABLE bank_details (
    id TEXT NOT NULL,
    candidate_id TEXT,
    account_holder_name VARCHAR(150),
    bank_name VARCHAR(150),
    account_number VARCHAR(50),
    ifsc_code VARCHAR(20),
    bank_proof_file_url TEXT,
    extracted_data JSON,
    verification_status VARCHAR(20),
    created_at TIMESTAMP,
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: candidates
-- -----------------------------
CREATE TABLE candidates (
    id TEXT NOT NULL,
    full_name VARCHAR(150),
    email VARCHAR(150),
    phone VARCHAR(20),
    dob DATE,
    gender VARCHAR(20),
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(50),
    pincode VARCHAR(10),
    onboarding_status VARCHAR(30),
    onboarding_source VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: employee_leave_balance
-- -----------------------------
CREATE TABLE employee_leave_balance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER NOT NULL,
    leave_type_id INTEGER NOT NULL,
    year INTEGER NOT NULL,
    total_quota INTEGER NOT NULL,
    used INTEGER,
    remaining INTEGER NOT NULL,
    carry_forwarded INTEGER,
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: employee_shifts
-- -----------------------------
CREATE TABLE employee_shifts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER,
    shift_id INTEGER,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: employees
-- -----------------------------
CREATE TABLE employees (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(20),
    designation VARCHAR(100),
    department VARCHAR(100),
    date_of_joining DATE,
    base_salary NUMERIC NOT NULL,
    status VARCHAR(20),
    created_at TIMESTAMP DEFAULT now(),
    manager_id INTEGER,
    PRIMARY KEY (employee_id)
);

-- -----------------------------
-- Table: holidays
-- -----------------------------
CREATE TABLE holidays (
    holiday_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    holiday_date DATE NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_optional BOOLEAN,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (holiday_id)
);

-- -----------------------------
-- Table: leave_balance
-- -----------------------------
CREATE TABLE leave_balance (
    balance_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER NOT NULL,
    leave_type_id INTEGER NOT NULL,
    year INTEGER NOT NULL,
    total_quota DOUBLE PRECISION NOT NULL,
    used DOUBLE PRECISION NOT NULL,
    remaining DOUBLE PRECISION NOT NULL,
    carry_forwarded DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (balance_id)
);

-- -----------------------------
-- Table: leave_history
-- -----------------------------
CREATE TABLE leave_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER NOT NULL,
    leave_type_id INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_days NUMERIC NOT NULL,
    recorded_on TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: leave_requests
-- -----------------------------
CREATE TABLE leave_requests (
    leave_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER NOT NULL,
    leave_type_id INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_days NUMERIC NOT NULL,
    reason TEXT,
    status VARCHAR(20),
    applied_on TIMESTAMP DEFAULT now(),
    approved_by INTEGER,
    approved_on TIMESTAMP,
    PRIMARY KEY (leave_id)
);

-- -----------------------------
-- Table: leave_types
-- -----------------------------
CREATE TABLE leave_types (
    leave_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(10) NOT NULL,
    yearly_quota INTEGER NOT NULL,
    is_paid BOOLEAN,
    carry_forward BOOLEAN,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (leave_type_id)
);

-- -----------------------------
-- Table: payroll
-- -----------------------------
CREATE TABLE payroll (
    payroll_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    working_days INTEGER,
    present_days INTEGER,
    total_hours NUMERIC,
    gross_salary NUMERIC,
    net_salary NUMERIC,
    generated_at TIMESTAMP DEFAULT now(),
    basic_pay NUMERIC,
    hra_pay NUMERIC,
    allowances_pay NUMERIC,
    overtime_hours NUMERIC,
    overtime_pay NUMERIC,
    late_penalty NUMERIC,
    early_penalty NUMERIC,
    lop_days NUMERIC,
    lop_deduction NUMERIC,
    night_shift_allowance NUMERIC,
    holiday_pay NUMERIC,
    is_finalized BOOLEAN,
    PRIMARY KEY (payroll_id)
);

-- -----------------------------
-- Table: payroll_lock
-- -----------------------------
CREATE TABLE payroll_lock (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    is_locked BOOLEAN NOT NULL,
    locked_at TIMESTAMP,
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: payroll_policies
-- -----------------------------
CREATE TABLE payroll_policies (
    policy_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    late_grace_minutes INTEGER,
    late_lop_threshold_minutes INTEGER,
    early_exit_grace_minutes INTEGER,
    early_exit_lop_threshold_minutes INTEGER,
    overtime_enabled BOOLEAN,
    overtime_multiplier NUMERIC,
    holiday_double_pay BOOLEAN,
    weekend_paid_only_if_worked BOOLEAN,
    night_shift_allowance NUMERIC,
    active BOOLEAN,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (policy_id)
);

-- -----------------------------
-- Table: request_status
-- -----------------------------
CREATE TABLE request_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    module VARCHAR(50) NOT NULL,
    request_id INTEGER NOT NULL,
    status VARCHAR(20),
    updated_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: salary_structure
-- -----------------------------
CREATE TABLE salary_structure (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER,
    basic NUMERIC NOT NULL,
    hra NUMERIC NOT NULL,
    allowances NUMERIC,
    deductions NUMERIC,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: shifts
-- -----------------------------
CREATE TABLE shifts (
    shift_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shift_name VARCHAR(100) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_night_shift BOOLEAN,
    created_at TIMESTAMP DEFAULT now(),
    break_start TIME,
    break_end TIME,
    break_minutes INTEGER,
    is_active BOOLEAN,
    break_grace_minutes INTEGER,
    break_required BOOLEAN,
    break_violation_action VARCHAR(20),
    required_hours NUMERIC NOT NULL,
    allow_early_overtime BOOLEAN,
    early_overtime_grace_minutes INTEGER,
    early_overtime_max_minutes INTEGER,
    early_overtime_requires_approval BOOLEAN,
    late_grace_minutes INTEGER NOT NULL,
    PRIMARY KEY (shift_id)
);

-- -----------------------------
-- Table: workflow_steps
-- -----------------------------
CREATE TABLE workflow_steps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workflow_id INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    role VARCHAR(50) NOT NULL,
    is_final BOOLEAN,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

-- -----------------------------
-- Table: workflows
-- -----------------------------
CREATE TABLE workflows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    module VARCHAR(50) NOT NULL,
    is_active BOOLEAN,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);
