import psycopg2
import json
from datetime import datetime, date
from decimal import Decimal

# ============================
# CONFIG – CHANGE ONLY THIS
# ============================
DB_CONFIG =  {
    "dbname": "hrms_db",
    "user": "varun",
    "password": "varun@123",
    "host": "localhost",
    "port": 5432,
}

OUTPUT_SCHEMA_FILE = "schema.sql"
OUTPUT_DATA_FILE = "data.sql"

# ============================
# HELPERS
# ============================

def sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float, Decimal)):
        return str(value)
    if isinstance(value, (datetime, date)):
        return f"'{value.isoformat()}'"
    if isinstance(value, dict):
        return "'" + json.dumps(value).replace("'", "''") + "'::jsonb"
    return "'" + str(value).replace("'", "''") + "'"

def normalize_type(data_type, char_len):
    if data_type in ("character varying", "varchar"):
        return f"VARCHAR({char_len})" if char_len else "TEXT"
    if data_type == "text":
        return "TEXT"
    if data_type == "integer":
        return "INTEGER"
    if data_type == "bigint":
        return "BIGINT"
    if data_type == "boolean":
        return "BOOLEAN"
    if data_type == "timestamp without time zone":
        return "TIMESTAMP"
    if data_type == "date":
        return "DATE"
    if data_type == "numeric":
        return "NUMERIC"
    if data_type == "jsonb":
        return "JSONB"
    if data_type == "time without time zone":
        return "TIME"
    return data_type.upper()

# ============================
# MAIN EXPORT
# ============================

conn = psycopg2.connect(**DB_CONFIG)
cur = conn.cursor()

# ----------------------------
# GET TABLES
# ----------------------------
cur.execute("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE'
    ORDER BY table_name
""")
tables = [row[0] for row in cur.fetchall()]

# ============================
# SCHEMA EXPORT
# ============================

schema_sql = []
schema_sql.append("-- ================================================")
schema_sql.append("-- HRMS SCHEMA EXPORT (Supabase Compatible)")
schema_sql.append("-- ================================================\n")

for table in tables:
    cur.execute("""
        SELECT
            column_name,
            data_type,
            character_maximum_length,
            is_nullable,
            column_default
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = %s
        ORDER BY ordinal_position
    """, (table,))
    columns = cur.fetchall()

    cur.execute("""
        SELECT a.attname
        FROM pg_index i
        JOIN pg_attribute a ON a.attrelid = i.indrelid
                           AND a.attnum = ANY(i.indkey)
        WHERE i.indrelid = %s::regclass
          AND i.indisprimary
    """, (table,))
    pk_cols = [r[0] for r in cur.fetchall()]

    schema_sql.append(f"-- -----------------------------")
    schema_sql.append(f"-- Table: {table}")
    schema_sql.append(f"-- -----------------------------")
    schema_sql.append(f"CREATE TABLE {table} (")

    col_defs = []
    for name, dtype, clen, nullable, default in columns:
        col_type = normalize_type(dtype, clen)

        # Replace sequences with IDENTITY
        if default and "nextval" in default:
            col_def = f"    {name} {col_type} GENERATED BY DEFAULT AS IDENTITY"
        else:
            col_def = f"    {name} {col_type}"
            if default and "now()" in default:
                col_def += " DEFAULT now()"

        if nullable == "NO":
            col_def += " NOT NULL"

        col_defs.append(col_def)

    if pk_cols:
        col_defs.append(f"    PRIMARY KEY ({', '.join(pk_cols)})")

    schema_sql.append(",\n".join(col_defs))
    schema_sql.append(");\n")

with open(OUTPUT_SCHEMA_FILE, "w") as f:
    f.write("\n".join(schema_sql))

# ============================
# DATA EXPORT
# ============================

data_sql = []
data_sql.append("-- ================================================")
data_sql.append("-- HRMS DATA EXPORT")
data_sql.append("-- ================================================\n")
data_sql.append("BEGIN;")
data_sql.append("SET session_replication_role = replica;\n")

for table in tables:
    cur.execute(f"SELECT * FROM {table}")
    rows = cur.fetchall()
    if not rows:
        continue

    col_names = [desc[0] for desc in cur.description]
    cols = ", ".join(col_names)

    data_sql.append(f"-- -----------------------------")
    data_sql.append(f"-- Table: {table}")
    data_sql.append(f"-- -----------------------------")

    for row in rows:
        values = ", ".join(sql_literal(v) for v in row)
        data_sql.append(f"INSERT INTO {table} ({cols}) VALUES ({values});")

    data_sql.append("")

data_sql.append("SET session_replication_role = DEFAULT;")
data_sql.append("COMMIT;")
data_sql.append("\n-- ================================================")
data_sql.append("-- END OF DATA EXPORT")
data_sql.append("-- ================================================")

with open(OUTPUT_DATA_FILE, "w") as f:
    f.write("\n".join(data_sql))

cur.close()
conn.close()

print("✅ Export completed successfully")
print(f"📄 Schema file: {OUTPUT_SCHEMA_FILE}")
print(f"📄 Data file:   {OUTPUT_DATA_FILE}")
